### ISSUE TITLE
Create installation instructions

### ISSUE THREAD

**Issue by tlovett1** [10up/snapshots#37]
We need installation instructions. This will be a public repo

**Comment by johnwatkins0** [comment]
@tlovett1 When installing a package from GitHub, WP CLI [supports a version constraint](https://developer.wordpress.org/cli/commands/package/install/). Do you think we should recommend installing a specific branch or release, or should we stick to the default version (which will install from the `trunk` branch of this repo)?

**Comment by tlovett1** [comment]
Is it possible to just install the latest release like npm?

**Comment by johnwatkins0** [comment]
@tlovett1 I will test it out. ~May need to make a release in this repo for testing purposes.~ Oops, I see you already did.
